#!/usr/bin/env python3
"""
Waveshare E-Paper Display - Web Configuration Interface
Author: Ravi

Run with: python3 web_interface.py
Access at: http://raspberrypi.local:5000
"""

from flask import Flask, render_template, request, jsonify, redirect, url_for
import os
import subprocess
import json
from datetime import datetime

app = Flask(__name__)

# Configuration file path
ENV_FILE = 'env.sh'
ENV_SAMPLE = 'env.sh.sample'

def read_env_file():
    """Read current env.sh configuration"""
    config = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith('export ') and '=' in line:
                    line = line.replace('export ', '')
                    key, value = line.split('=', 1)
                    # Remove quotes if present
                    value = value.strip('"').strip("'")
                    config[key] = value
    return config

def write_env_file(config):
    """Write configuration to env.sh"""
    with open(ENV_FILE, 'w') as f:
        f.write('#!/usr/bin/env bash\n\n')
        f.write('# Generated by Web Interface on {}\n\n'.format(datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
        
        # Todoist
        f.write('# ========== TODOIST CONFIGURATION ==========\n')
        if config.get('TODOIST_API_TOKEN'):
            f.write('export TODOIST_API_TOKEN="{}"\n'.format(config.get('TODOIST_API_TOKEN', '')))
        f.write('\n')
        
        # Weather Provider
        f.write('# ========== WEATHER CONFIGURATION ==========\n')
        if config.get('METNO_SELF_IDENTIFICATION'):
            f.write('export METNO_SELF_IDENTIFICATION="{}"\n'.format(config.get('METNO_SELF_IDENTIFICATION', '')))
        if config.get('OPENWEATHERMAP_APIKEY'):
            f.write('export OPENWEATHERMAP_APIKEY="{}"\n'.format(config.get('OPENWEATHERMAP_APIKEY', '')))
        if config.get('VISUALCROSSING_APIKEY'):
            f.write('export VISUALCROSSING_APIKEY="{}"\n'.format(config.get('VISUALCROSSING_APIKEY', '')))
        
        f.write('export WEATHER_LATITUDE="{}"\n'.format(config.get('WEATHER_LATITUDE', '51.5077')))
        f.write('export WEATHER_LONGITUDE="{}"\n'.format(config.get('WEATHER_LONGITUDE', '-0.1277')))
        f.write('export WEATHER_FORMAT="{}"\n'.format(config.get('WEATHER_FORMAT', 'CELSIUS')))
        f.write('\n')
        
        # Display
        f.write('# ========== DISPLAY CONFIGURATION ==========\n')
        f.write('export WAVESHARE_EPD75_VERSION="{}"\n'.format(config.get('WAVESHARE_EPD75_VERSION', '2')))
        f.write('export SCREEN_LAYOUT="{}"\n'.format(config.get('SCREEN_LAYOUT', '1')))
        f.write('\n')
        
        # Cache
        f.write('# ========== CACHE SETTINGS ==========\n')
        f.write('export WEATHER_TTL="{}"\n'.format(config.get('WEATHER_TTL', '3600')))
        f.write('export CALENDAR_TTL="{}"\n'.format(config.get('CALENDAR_TTL', '3600')))
        f.write('\n')
        
        # Logging
        f.write('# ========== LOGGING ==========\n')
        f.write('export LOG_LEVEL="{}"\n'.format(config.get('LOG_LEVEL', 'INFO')))
        f.write('\n')
        
        # Privacy
        f.write('# ========== PRIVACY MODE ==========\n')
        f.write('export PRIVACY_MODE_XKCD="{}"\n'.format(config.get('PRIVACY_MODE_XKCD', '0')))
        f.write('export PRIVACY_MODE_LITERATURE_CLOCK="{}"\n'.format(config.get('PRIVACY_MODE_LITERATURE_CLOCK', '0')))

def get_display_status():
    """Get current display status"""
    status = {
        'last_update': 'Unknown',
        'cache_files': [],
        'log_size': 0
    }
    
    # Check log file
    if os.path.exists('run.log'):
        stat = os.stat('run.log')
        status['log_size'] = stat.st_size
        status['last_update'] = datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S')
    
    # Check cache files
    cache_files = ['cache_weather.json', 'cache_todoist.pickle', 'cache_calendar.pickle']
    for cache_file in cache_files:
        if os.path.exists(cache_file):
            stat = os.stat(cache_file)
            status['cache_files'].append({
                'name': cache_file,
                'age': datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S')
            })
    
    return status

@app.route('/')
def index():
    """Main dashboard"""
    config = read_env_file()
    status = get_display_status()
    return render_template('index.html', config=config, status=status)

@app.route('/save', methods=['POST'])
def save_config():
    """Save configuration"""
    try:
        config = request.form.to_dict()
        write_env_file(config)
        return jsonify({'success': True, 'message': 'Configuration saved successfully!'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@app.route('/update', methods=['POST'])
def update_display():
    """Trigger display update"""
    try:
        result = subprocess.run(['bash', 'run.sh'], capture_output=True, text=True, timeout=60)
        return jsonify({
            'success': result.returncode == 0,
            'output': result.stdout,
            'error': result.stderr
        })
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@app.route('/clear-cache', methods=['POST'])
def clear_cache():
    """Clear cache files"""
    try:
        cache_files = ['cache_weather.json', 'cache_todoist.pickle', 'cache_calendar.pickle']
        removed = []
        for cache_file in cache_files:
            if os.path.exists(cache_file):
                os.remove(cache_file)
                removed.append(cache_file)
        return jsonify({'success': True, 'removed': removed})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

@app.route('/logs')
def view_logs():
    """View log file"""
    try:
        if os.path.exists('run.log'):
            with open('run.log', 'r') as f:
                logs = f.readlines()[-100:]  # Last 100 lines
            return jsonify({'success': True, 'logs': ''.join(logs)})
        return jsonify({'success': False, 'message': 'No log file found'})
    except Exception as e:
        return jsonify({'success': False, 'message': str(e)})

if __name__ == '__main__':
    # Create env.sh from sample if it doesn't exist
    if not os.path.exists(ENV_FILE) and os.path.exists(ENV_SAMPLE):
        subprocess.run(['cp', ENV_SAMPLE, ENV_FILE])
    
    # Run on all interfaces so it's accessible from other devices
    app.run(host='0.0.0.0', port=5001, debug=True)
